# Generated by Django 4.2.2 on 2024-02-07 01:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=100)),
                ('activites_disponibles', models.CharField(max_length=255)),
                ('informations_geographiques', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_l_evenement', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=100)),
                ('categorie_sportive', models.CharField(max_length=255)),
                ('prix_d_inscription', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('caractere_long_variable', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('prénom', models.CharField(default='', max_length=255)),
                ('email_adress', models.EmailField(default='', max_length=255)),
                ('mot_de_passe', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_reservation', models.DateTimeField(default=datetime.datetime.now)),
                ('statut_de_la_reservation', models.CharField(max_length=255)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarocSport.utilisateur')),
            ],
        ),
    ]
